name: Build docker image

on:
  push:
    branches:
      - main

env:
  METABASE_VERSION: v0.50.14

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64

      - name: Downcase repo name
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v6.5.0
        with:
          push: true
          context: .
          platforms: linux/arm64
          build-args: |
            METABASE_VERSION=${{ env.METABASE_VERSION }}
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.METABASE_VERSION }}
